::python findreplace.py C:\Users\zhoufan\Projects\Python\LibraryTest\source "*.py" "tab" "    " 
::python findreplace.py C:\Users\zhoufan\Projects\Python\TrumCloud\app\urlmap "*.py" "tab" "    " 
::python findreplace.py C:\Users\zhoufan\Projects\Python\TrumCloud\app "*.py" "tab" "    " 
::python findreplace.py C:\Users\zhoufan\Projects\Python\TrumCloud\app "*.py" "\"ERROR\"" "RESULT.ERROR" 
::python findreplace.py C:\Users\zhoufan\Projects\Python\TrumCloud\app\templates\bingo "*.js" "'OK'" "'{{appctx.RESULT.OK}}'"
::python findreplace.py C:\Users\zhoufan\Projects\Python\TrumCloud\app\static\bingo\myjs "*.js" "tab" "    " 
python findreplace.py C:\Users\zhoufan\Projects\Python\TrumCloud\app\templates\bingo "*.html;*.js" "tcld_cfg.STATIC_DIR" "STATIC_DIR" 